### PR TITLE
commit of zach-log-in-page clone

### PR DESCRIPTION
**Pull request by ZachDFK**
Hopefully the last will see of the zach-log-in-page commit saga.

### CODE REVIEW

**Comment by kevincox** [comment]
This isn't going to work. It looks like you overwrote a bunch of master.

**Comment by ZachDFK** [comment]
That's what I was afraid of...

**Comment by kevincox** [comment]
If you are going to copy-paste your changes on top you need to ensure that you paste them on top of the commit your changes were based off of. Or else you are undoing all of the changes since.

**Comment by ZachDFK** [comment]
Alright I'll close this PR, it was worth a shot I guess.

**Pull request closed without merging**
